### ISSUE TITLE
Stringifiability of other Node properties

### ISSUE THREAD

**Issue by eush77** [wooorm/unist#5]
Do they have to be JSON-stringifiable as well? (I think they should.)

If they better be, is there a way to specify this?

**Comment by wooorm** [comment]
Then you’re talking about properties not in the Unist core, such as `start` as defined by MDAST on the `list` node?

Anyway, this is related to what happens in GH-4.

**Comment by eush77** [comment]
> Then you’re talking about properties not in the Unist core, such as start as defined by MDAST on the list node?

Yeah, that.

**Comment by eush77** [comment]
Closed in favor of #4.
