### ISSUE TITLE
adast - asciidoc syntax tree

### ISSUE THREAD

**Issue by bguiz** [wooorm/unist#8]
Came across unist & remark via mdast, and I was wondering what would be involved in creating an entirely new flavour of syntax tree within this family?

More concretely, I'm interested in creating `adast`, an asciidoc syntax tree, and while the input format is rather different from markdown, there's potentially a huge chunk of the implementation that could potentially be same or similar to that of `mdast`, as the output is going to be quite similar to it.

Thoughts?

**Comment by wooorm** [comment]
Cool!

> Came across unist & remark via mdast, and I was wondering what would be involved in creating an entirely new flavour of syntax tree within this family?

The syntax definition wouldn’t be very involved. In fact, maybe you could even adopt [HAST](https://github.com/wooorm/hast) for that (thought about this for MDAST as well, but some stuff doesn’t make sense).

In my experience, getting the whole project off the ground (mdast comes with the remark parser and compiler, and a lot of plugins) takes roughly a year. retext took a year, remark another, and rehype is going to take something like that as well 😕

> More concretely, I'm interested in creating adast, an asciidoc syntax tree, and while the input format is rather different from markdown, there's potentially a huge chunk of the implementation that could potentially be same or similar to that of mdast, as the output is going to be quite similar to it.

I’m not too familiar with asciidoc, do you have an exhaustive list of elements which I could take a look at? That would enable me to give some more specific pointers.

**Comment by bguiz** [comment]
> I’m not too familiar with asciidoc, do you have an exhaustive list of elements which I could take a look at? That would enable me to give some more specific pointers.

[Quick reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) - Covers the most commonly used elements

[Cheat sheet](https://powerman.name/doc/asciidoc) - Covers recipes of typical ways in which the elements are combined

It is worth noting that the current implementations for asciidoc are largely based on regular expressions, that could frame the work involved in the parsing.

> In my experience, getting the whole project off the ground (mdast comes with the remark parser and compiler, and a lot of plugins) takes roughly a year. retext took a year, remark another, and rehype is going to take something like that as well

So remark/ retext/ rehype are specific to mdast? (I was hoping those could be re-used to some extent when parsing other syntxax types)

**Comment by wooorm** [comment]
> Quick reference - Covers the most commonly used elements

> Cheat sheet - Covers recipes of typical ways in which the elements are combined

From what I read there, asciidoc's (for example, as there's specific stylesheets involved) purpose is always to compile to HTML, thus maybe HAST is good enough for representing the nodes.
MDAST is separate because, for one, I saw it being used more and more without the goal of rendering to HTML.

> So remark/ retext/ rehype are specific to mdast? (I was hoping those could be re-used to some extent when parsing other syntxax types)

No, that’s not what I’m saying. remark is intertwined, but retext and rehype are not. 

I suggest reading the readme of [unified](https://github.com/wooorm/unified), and seeing how [remark](https://github.com/wooorm/remark/tree/master/packages)/[retext](https://github.com/wooorm/retext/tree/master/packages), and [rehype](https://github.com/wooorm/rehype/tree/master/packages) are structured.

**Comment by bguiz** [comment]
So asciidoc actually has multiple targets: HTML, PDF, EPUB (and others)

Thanks, I'll look into unified and the lot!

**Comment by wooorm** [comment]
I don’t think this should be an issue over here.
If you’d want to commit to working on this, let’s talk about it on it’s own repo?

**Comment by tats-u** [comment]
Someone finally made one:

- [@asciidoc-js/adast-util-from-asciidoc](https://www.npmjs.com/package/%40asciidoc-js%2Fadast-util-from-asciidoc)
- [@asciidoc-js/adast-util-to-mdast](https://www.npmjs.com/package/%40asciidoc-js%2Fadast-util-to-mdast)
